export const styles = {
  root: {
    background: "transparent",
    borderRadius: "5px",
    padding: "5px",
    overflow: "hidden",
    cursor: "pointer",
    minWidth: "175px",
    width: "95%",
    height: "95%",
    transition: " all 0.2s linear",
    "&:hover": {
      boxShadow: "0px 5px .5rem #00000045",
      background: "white",
    },
    "&:hover svg": {
      opacity: "1",
    },
  },
  colors: {
    background: "transparent",

    height: "150px",
    width: "100%",
    borderRadius: "5px",
    overflow: "hidden",
    display: "flex",
    flexWrap: "wrap",
  },
  title: {
    color: "black",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    margin: "0",
    paddingTop: "0.5rem",
    fontSize: "1rem",
    fontWeight: "400",
    position: "relative,",
    textTransform: "capitalize",
  },
  emoji: { marginLeft: "0.5rem", fontSize: "1.5rem" },
  colorBox: {
    width: "20%",
    height: "25%",
    // display: "inline-block",
    // margin: "0 auto",
    // position: "relative",
    // marginBottom: "-3.5px",
  },
  delete: {
    position: "relative",
  },
  deleteIcon: {
    color: "white",
    right: "0",
    position: "absolute",
    top: "0",
    height: "2rem",
    width: "2rem",
    zIndex: " 1",
    padding: ".5rem",
    opacity: "0",
    backgroundColor: "red",
    transition: "all 0.2s ease",
  },
};
